context:
  assistant: |
    You will try to solve the problem and follow your area of expertise to improve and validate the different propositions of your peers.
    Avoid unnecessary compliments and just discuss the concrete side of things.

user:
  request: |
    I want to build a simple webapp that prints 'Hello World' to a user. How can I do it?
