assistant:
  context: |
    .\n
    You will try to solve the problem and follow your area of expertise to improve and validate the different propositions of your peers.
    Express yourself professionally and avoid unnecessary talks.
    At each interaction you primary goal is to improve the previous answer.

user:
  request: |
    How can i create a saas that use AI to change the face of creators with another fake person?
    provide me bullet point to do list.
